/**
 * Idempotently seeds the canonical reference network on every startup, mirroring
 * user-service's permission bootstrap. Reference data (operator, stops, buses,
 * routes, ordered route-stops, fares) is what the service needs to function at
 * all — without stops there are no locations, without routes/fares no bookings.
 *
 * Everything is upserted on a stable natural key so existing rows keep their ids
 * (tickets and trips reference stop/route ids — they must never churn):
 *   organisation → id          stop  → name (unique)     bus   → plate (unique)
 *   route        → slug        route_stop → (route, order)   price → (boarding, alighting)
 *
 * Operational data (trips, tickets) is NEVER touched here — that is generated by
 * the dev seed script or, in production, created through the API / schedulers.
 */
import { randomUUID } from 'node:crypto';
import { prisma } from '../models/index.js';
import { ORG, STOPS, ROUTES, PRICES, BUSES, slugify, routeDurationMin } from '../data/network.js';

export interface BootstrapResult {
  /** stop name → id */
  stopId: Record<string, string>;
  /** route name → { id, durationMin } */
  routes: { name: string; id: string; durationMin: number }[];
  /** bus plate → { id, total_seats } */
  buses: Record<string, { id: string; total_seats: number }>;
}

export const bootstrap = async (): Promise<BootstrapResult> => {
  // ── 1. Operator ───────────────────────────────────────────────────────────
  // Normally synced from user-service org events; upserted here so the network's
  // FKs resolve even before the first event arrives.
  await prisma.organisation.upsert({
    where: { id: ORG.id },
    create: { id: ORG.id, name: ORG.name, slug: ORG.slug, org_type: 'company', status: 'active', tin: ORG.tin, cancellation_allowed: true },
    update: {},
  });

  // ── 2. Stops ────────────────────────────────────────────────────────────────
  const stopId: Record<string, string> = {};
  for (const [name, [lat, lng]] of Object.entries(STOPS)) {
    const stop = await prisma.stop.upsert({
      where: { name },
      create: { id: randomUUID(), name, city: name, lat, lng },
      update: { lat, lng },
    });
    stopId[name] = stop.id;
  }

  // ── 3. Buses ─────────────────────────────────────────────────────────────────
  const buses: Record<string, { id: string; total_seats: number }> = {};
  for (const b of BUSES) {
    const bus = await prisma.bus.upsert({
      where: { plate: b.plate },
      create: { id: randomUUID(), org_id: ORG.id, plate: b.plate, type: b.type, total_seats: b.total_seats },
      update: { type: b.type, total_seats: b.total_seats },
    });
    buses[b.plate] = { id: bus.id, total_seats: bus.total_seats };
  }

  // ── 4. Routes + ordered stops ────────────────────────────────────────────────
  const routes: { name: string; id: string; durationMin: number }[] = [];
  for (const r of ROUTES) {
    const slug = slugify(r.name);
    const route = await prisma.route.upsert({
      where: { slug },
      create: {
        id: randomUUID(), org_id: ORG.id, name: r.name, slug,
        origin_stop_id: stopId[r.stops[0]], destination_stop_id: stopId[r.stops[r.stops.length - 1]],
      },
      update: {
        name: r.name,
        origin_stop_id: stopId[r.stops[0]], destination_stop_id: stopId[r.stops[r.stops.length - 1]],
      },
    });

    for (let i = 0; i < r.stops.length; i++) {
      await prisma.routeStop.upsert({
        where: { route_id_order: { route_id: route.id, order: i + 1 } },
        create: { id: randomUUID(), route_id: route.id, stop_id: stopId[r.stops[i]], order: i + 1 },
        update: { stop_id: stopId[r.stops[i]] },
      });
    }

    routes.push({ name: r.name, id: route.id, durationMin: routeDurationMin(r.stops) });
  }

  // ── 5. Fares (both directions) ───────────────────────────────────────────────
  let fareCount = 0;
  for (const [a, b, amount] of PRICES) {
    if (!stopId[a] || !stopId[b]) {
      console.warn('[bootstrap] missing stop for fare', a, b);
      continue;
    }
    for (const [x, y] of [[a, b], [b, a]]) {
      await prisma.price.upsert({
        where: { boarding_stop_id_alighting_stop_id: { boarding_stop_id: stopId[x], alighting_stop_id: stopId[y] } },
        create: { id: randomUUID(), boarding_stop_id: stopId[x], alighting_stop_id: stopId[y], amount },
        update: { amount },
      });
      fareCount++;
    }
  }

  console.warn(
    `[bootstrap] ${Object.keys(stopId).length} stops, ${Object.keys(buses).length} buses, ` +
    `${routes.length} routes, ${fareCount} fares synced`,
  );

  return { stopId, routes, buses };
};
